### PR TITLE
Remove css from lib

### LINKED ISSUE #93: compile the library to remove the reference of CSS files from node_modules
When we use this library with the latest version of Next.Js this error is thrown.

> CSS Imported by a Dependency
> Why This Error Occurred
> One of your dependencies (node_modules) imports a CSS file.
> 
> This normally happens when a package's source files are accidentally consumed, instead of the built package.
> 
> Possible Ways to Fix It
> Reach out to the maintainer and ask for them to publish a compiled version of their dependency.
> 
> Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations.
> 
> The dependency should also provide instructions about what CSS needs to be imported by you, in your application.
> 
> Importing CSS files within node_modules cannot be supported because we cannot know the correct behavior:
> 
> Should the file be consumed as Global CSS or CSS Modules?
> If Global, in what order does the file need to be injected?
> If Modules, what are the emitted class names? As-is, camel-case, snake case?

https://github.com/zeit/next.js/blob/master/errors/css-npm.md

Can we get a quick fix for this issue??

### PR DESCRIPTION
**Pull request by raajnadar**
Fix https://github.com/firebase/firebaseui-web-react/issues/93

Removed the css required from the js file and ask the user to import them manually from the node_modules so that it works with next js.

### CODE REVIEW

**Comment by raajnadar** [comment]
@googlebot I signed it!

**Comment by ssijak** [comment]
I have the same problem and would like for this pull request to be considered.

**Comment by asarazan** [comment]
Can we get some attention on this PR?

**Comment by landsman** [comment]
Yes pls!

**Comment by cairomassimo** [comment]
Merging this is a no-brainer.

_React_ libraries should not assume working with _Create React App_ with its specific Webpack configuration, only React. It's so simple and blocks a large number of users...

**Comment by raajnadar** [comment]
Merge conflicts resolved

**Comment by jhuleatt** [comment]
Sorry for the delay here. I just wanted to check - isn't this problem solved by `StyledFirebaseAuth`? It [bundles the CSS directly](https://github.com/firebase/firebaseui-web-react#firebaseauth-vs-styledfirebaseauth), so there shouldn't be a `require` call.

**Comment by jhuleatt** [comment]
Some extra context: https://github.com/firebase/firebaseui-web-react/issues/10#issuecomment-364757047

**Comment by raajnadar** [comment]
@jhuleatt if you think this PR is not useful you can close this 👍🏻

**Comment by jhuleatt** [comment]
I'd like to make sure we understand the problem before closing - does `StyledFirebaseAuth` solve your use case?

**Comment by raajnadar** [comment]
Actually this is a very old PR and I no longer use this library so I cannot say anything about it.

**Comment by landsman** [comment]
@jhuleatt hey guys, why this is closed? It was useful. Import of styles should be optional. 😢

**Comment by jhuleatt** [comment]
@landsman this was closed because, as far as I can tell, `StyledFirebaseAuth` solves the same problem this PR was trying to solve (see my comments above). If you disagree, happy to discuss.

**Pull request closed without merging**
