### PR TITLE
Misleading example for redirect mode

### PR DESCRIPTION
**Pull request by paramaggarwal**
Just a documentation update.

### CODE REVIEW

**Comment by bojeil-google** [comment]
This example is not useful. `redirect` mode is the default mode. We should document switching to `popup` as is the current case.

**Comment by bojeil-google** [comment]
We should update this line:
`Below is an example on how to use `FirebaseAuth` with a redirect upon sign-in:`

to:
`Below is an example on how to use `FirebaseAuth` with a popup upon sign-in:`

**Comment by bojeil-google** [comment]
It's a bit confusing. So there are 2 options here:
1. sign in to IdP with popup (using `signInFlow`) and then redirect to sign in success URL. (existing example)
2. sign in to IdP with redirect (using `signInFlow`) and then redirect to sign in success URL. (proposed change)

For (2), the `signInFlow` is `redirect` by default. It doesn't even need to be specified.

**Comment by paramaggarwal** [comment]
Hi @bojeil-google I am confused - I was just fixing a typo in the existing example. It was an example referring to redirect but then it shows popup in the code sample.

Please guide me on what I should change here. I'll make the changes. Thanks.

**Comment by paramaggarwal** [comment]
If you look above the code block where I have made the change it says this:

> Below is an example on how to use `FirebaseAuth` with a redirect upon sign-in:

**Comment by bojeil-google** [comment]
I explained in my comment earlier. There are 2 redirects involved in the end-to-end flow (one to IdP and another to sign-in success URL). `signInFlow` is only relevant to the IdP redirect. I am fine with your change but `signInFlow` is `redirect` by default. It doesn't even need to be specified in this case. There is more value in  documenting the IdP `popup` flow. If you can add that additional documentation via comment, then I think this should be good.

**Comment by paramaggarwal** [comment]
Screenshot 2020-04-10 at 6 54 39 PM

**Comment by wshin387** [comment]
image

**Pull request closed without merging**
