### PR TITLE
Update firebase-ui dependency to support Auth emulator

### PR DESCRIPTION
**Pull request by chetbox**
Updates the `firebase-ui` dependency to support Firebase Auth emulator

Resolves ﻿#118

### CODE REVIEW

**Comment by chetbox** [comment]
@googlebot I signed it!

**Comment by locona** [comment]
Any updates to this PR?

**Comment by zackdotcomputer** [comment]
Trying this change locally, my `StyledFirebaseAuth` component does not successfully call-back from an emulated auth when using fake-Twitter. I'm assuming this is a bug higher up the chain and not merge-blocking for this but figured I'd report it.

**Comment by zackdotcomputer** [comment]
Yup confirmed this is an issue with the base firebase-web SDK [tracked here](https://github.com/firebase/firebaseui-web/issues/822)

**Comment by paymog** [comment]
@zackdotcomputer how did you test this locally? It seems like this hasn't been merged yet nor published as a package.

**Review by paymog — APPROVED** [review]

**Comment by zackdotcomputer** [comment]
@paymog I did actually test this in my project. Personally I tested it by using the package.json `resolutions` field to override the `react-firebaseui/firebaseui` version, recreating the same effect that this PR would have when merged.

You could also test it more directly by depending directly on the code from @chetbox's github with `npm install --save chetbox/firebaseui-web-react#update-firebase-ui`

**Comment by jhuleatt** [comment]
Hey @chetbox thanks for the PR! Since there are some merge conflicts after #122, I updated the `firebase-ui` dependency in commit https://github.com/firebase/firebaseui-web-react/commit/54cc2eba872f633237614f3a18f8436d65be2013 and gave you co-author credit. It's now available in `react-firebaseui@5.0.1`

**Comment by chetbox** [comment]
Thanks @jhuleatt!

**Pull request closed without merging**
