### PR TITLE
Support React 18

### LINKED ISSUE #165: Support React 18

### PR DESCRIPTION
**Pull request by OrhanTozan**
Closes #165.

### CODE REVIEW

**Comment by Joshuatanderson** [comment]
Is there anything stopping this from being merged?  This is holding me up right now.  

Cheers, and thanks, @OrhanTozan.

**Comment by Pranavb333** [comment]
Firebase Auth does not work in strict mode when using React 18, see #172 for more details.

Until that is resolved and the PR is merged, you could try using -
`npm install --save --legacy-peer-deps react-firebaseui`

**Comment by Joshuatanderson** [comment]
Unfortunately, that doesn't seem to work well for me, @OrhanTozan.  I might be down on this one until a fix is in place.  Thanks for the idea though!

**Comment by jonasmeisner** [comment]
What's the timeline for the merge? This is really holding me back right now.

**Pull request closed without merging**
