### PR TITLE
Add `types` property to package

### PR DESCRIPTION
**Pull request by ShaMan123**
This exposes types for the compiler
Continues #48

### CODE REVIEW

**Comment by landsman** [comment]
nice!

**Comment by jhuleatt** [comment]
Thanks @ShaMan123! 

@jamesdaniels this looks like a helpful fix to me, but wanted to double check with you before merging.

**Comment by landsman** [comment]
pls 🙏

**Comment by jhuleatt** [comment]
After looking into this a bit more and chatting with @jamesdaniels , we are shipping an `index.d.ts` (which Typescript looks for implicitly), and in a test project I was able to get the types as-is, without the need for a `types` field.

I'm going to close this out, but if I'm misunderstanding, please comment and we can discuss.

**Comment by landsman** [comment]
@jhuleatt Can you say future version number with this pls?

**Comment by jhuleatt** [comment]
The latest version on npm, `6.0.0`, has types.

**Pull request closed without merging**
