### PR TITLE
Update dependencies: 🔥 Firebase 8 and ⚛️ React 17

### PR DESCRIPTION
**Pull request by jhuleatt**
- Match [firebaseui-web's Firebase `peerDependencies` version](https://github.com/firebase/firebaseui-web/blob/6525220b5dccdac769692592b79f392aef08ed1b/package.json#L64-L66)
- React 17
- Update some other dependencies
- Fix example's `createfirebaseconf` script

### CODE REVIEW

**Comment by jhuleatt** [comment]
This has been published to npm with a `canary` tag. Try it out by running:

```bash
npm install react-firebaseui@canary
```

**Comment by brendanmc6** [comment]
Sorry if this is a stupid question, will this fix this import error? https://github.com/firebase/firebaseui-web-react/issues/114
```
Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase').
```
Just asking because I couldn't spot any relevant changes in the diff.

**Comment by HugoGresse** [comment]
I had almost no issue with the canary yet, no import issue (React 17)
The only things was that I needed it to pin the firebaseui version to 4.7.3 to benefit for the auth emulator fixes.

**Comment by OrhanTozan** [comment]
@jhuleatt Sorry for asking, but why is this still not merged to master after 4 months? 😀

**Comment by david-wb** [comment]
Please merge this soon. Firebase 8 has been out for 5 months.

**Comment by tomseago** [comment]
Not to dog-pile, but yeah, would love to drop the need for @canary on this one...

**Comment by chris-rock** [comment]
@samtstern Can you help with this? It would be great if the react plugin moves forward.

**Comment by jhuleatt** [comment]
react-firebaseui version `5.0.0` has been published

**Pull request merged**
